[package]
name = "Guessing-Game"
version = "0.1.0"
authors = ["tatsu"]
edition = "2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"